SupplyChainManagement/Controllers/EmailController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SupplyChainManagement.Controllers
{
    public class EmailController : Controller
    {
        private readonly IEmailSender _emailSender;
     public EmailController(IEmailSender emailSender)
        {
            _emailSender = emailSender;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult SendEmail()
        {
            return View();
        }
        [HttpPost]
        public async Task<string> SendEmail(IEnumerable<string> to, string subject, string content, IFormFileCollection attachments)
        {
          
            try
            { 
                var rng = new Random();
                attachments = Request.Form.Files.Any() ? Request.Form.Files : new FormFileCollection();
                var message = new Message();
                {
                    message.To = new List<MailboxAddress>();
                    message.Subject = subject;
                    message.Content = content;
                    message.Attachments = attachments;
                };
                message.To.AddRange(to.Select(x => new MailboxAddress(x)));
                await _emailSender.SendEmailAsync(message);
            }
            catch(Exception ex)
            {
                throw ex;
            }
            return "Email sent successfully!!";
        }
        }
    }

SupplyChainManagement/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Entities;
using Entities.Models;
using Microsoft.AspNetCore.Http;
using Services;
using Microsoft.Extensions.Configuration;
using System.Net.Mail;
using System.Net;

//using SearchSortPaging;

namespace SupplyChainManagement.Controllers
{
    public class SupplierController : Controller
    {
        private readonly RepositoryContext _context;
        public static int? CurrentSupplierId;

        public static string  RequisitionItem;
        public static string  ReqItemDescription;
        public static string  ReqSupplierName;
        public static int?    ReqQuantity;
        public static string RFQRequisitionId; 
        private readonly IEmailSender _emailSender;
        private IConfiguration configuration;

        public SupplierController(RepositoryContext context ,IEmailSender emailSender, IConfiguration iConfig)
        {
            _context = context;
            _emailSender = emailSender;
            configuration = iConfig;
            //ViewData["MessageCount"] = 1;

        }

        // GET: Supplier
        public async Task<IActionResult> Index()
        {
          
            var repositoryContext = _context.Supplier.Include(s => s.City).Include(s => s.Classification).Include(s => s.Country).Include(s => s.Municipality).Include(s => s.PaymentMethod).Include(s => s.Province).Include(s => s.Ward);
            return View(await repositoryContext.ToListAsync());
        }

        // GET: Supplier/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            CurrentSupplierId = id;
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Supplier
                .Include(s => s.City)
                .Include(s => s.Classification)
                .Include(s => s.Country)
                .Include(s => s.Municipality)
                .Include(s => s.PaymentMethod)
                .Include(s => s.Province)
                .Include(s => s.Ward)
                .FirstOrDefaultAsync(m => m.SupplierId == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        public async Task<IActionResult> SupplierSearchDetails(int? id)
        {
            CurrentSupplierId = id;
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Supplier
                .Include(s => s.City)
                .Include(s => s.Classification)
                .Include(s => s.Country)
                .Include(s => s.Municipality)
                .Include(s => s.PaymentMethod)
                .Include(s => s.Province)
                .Include(s => s.Ward)
                .FirstOrDefaultAsync(m => m.SupplierId == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }
        [HttpPost]
        public async Task<IActionResult> RequisitionToSupplier(IFormCollection Form)
        {
            ViewBag.Name = Form["reqNumber"];
            RFQRequisitionId = ViewBag.Name; 
            if (CurrentSupplierId == null)
            {
                return NotFound();
            }

            var supplier = await _context.Supplier
                .Include(s => s.City)
                .Include(s => s.Classification)
                .Include(s => s.Country)
                .Include(s => s.Municipality)
                .Include(s => s.PaymentMethod)
                .Include(s => s.Province)
                .Include(s => s.Ward)
                .FirstOrDefaultAsync(m => m.SupplierId == CurrentSupplierId);
            if (supplier == null)
            {
                return NotFound();
            }
            var  reqNumber = ViewBag.Name;
            Guid requisitionNo =  Guid.Parse(reqNumber);
            var repositoryContext = _context.Requisition.ToList().Find(x => x.RequisitionNo == requisitionNo);

            RequisitionItem = repositoryContext.Item;
            ReqItemDescription = repositoryContext.ItemDescription;
            ReqQuantity = repositoryContext.Quantity;


            var supplierDetails = _context.Supplier.ToList().Find(x => x.SupplierId == CurrentSupplierId);

            ReqSupplierName = supplierDetails.SupplierName;
            ViewData["requisitionDetails"] = repositoryContext;
            ViewData["selectedSupplierDetails"] = supplierDetails;
            //ViewData["selectedSupplierDetails"] = new SelectList(supplierDetails, "Id", "Display)
            return View("SupplierSearchDetails");
        }

        public IActionResult Create()
        {
            ViewData["CityId"] = new SelectList(_context.City, "CityId", "CityId");
            ViewData["ClassificationId"] = new SelectList(_context.Classification, "ClassificationId", "Description");
            ViewData["CountryId"] = new SelectList(_context.Country, "CountryId", "CountryId");
            ViewData["MunicipalityId"] = new SelectList(_context.Municipality, "MunicipalityId", "MunicipalityAddress");
            ViewData["PaymentMethodId"] = new SelectList(_context.PaymentMethod, "PaymentMethodId", "Description");
            ViewData["ProvinceId"] = new SelectList(_context.Province, "ProvinceId", "ProvinceName");
            ViewData["WardId"] = new SelectList(_context.Ward, "WardId", "WardName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("SupplierId,SupplierName,ClassificationId,LegalName,RegistrationNo,Vatregistered,VatregistrationNo,Bbbeeid,Currency,PaymentMethodId,PaymentTermId,StreetName,BuildingName,Surburb,CityId,ProvinceId,MunicipalityId,WardId,PostalCode,CountryId,ContactPersonName,ContactPersonSurname,ContactPersonPosition,ContactPersonTelephone,ContactPersonFax,ContactPersonCell,ContactPersonEmail,QuotationContact")] Supplier supplier)
        {
            //if(supplier.SupplierId ==0)
            //{
            //    await SendRFQEmailAsync();
            //}
            
            if (ModelState.IsValid)
            {
                supplier.BuildingName = "building";
                supplier.ContactPersonCell = "0812344321";
                _context.Add(supplier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CityId"] = new SelectList(_context.City, "CityId", "CityId", supplier.CityId);
            ViewData["ClassificationId"] = new SelectList(_context.Classification, "ClassificationId", "Description", supplier.ClassificationId);
            ViewData["CountryId"] = new SelectList(_context.Country, "CountryId", "CountryId", supplier.CountryId);
            ViewData["MunicipalityId"] = new SelectList(_context.Municipality, "MunicipalityId", "MunicipalityAddress", supplier.MunicipalityId);
            ViewData["PaymentMethodId"] = new SelectList(_context.PaymentMethod, "PaymentMethodId", "Description", supplier.PaymentMethodId);
            ViewData["ProvinceId"] = new SelectList(_context.Province, "ProvinceId", "ProvinceName", supplier.ProvinceId);
            ViewData["WardId"] = new SelectList(_context.Ward, "WardId", "WardName", supplier.WardId);
            return View(supplier);
        }

        [HttpPost]
        public async Task<IActionResult> SendRFQ(IFormCollection Form)
        {
  

            var supplierDetails = _context.Supplier.ToList().Find(x => x.SupplierId == CurrentSupplierId);
            ViewData["selectedSupplierDetails"] = supplierDetails;
            //ViewBag.Name = Form["quoteReqId"];
            //string TransactionNo = ViewBag.Name;
            string TransactionNo = RFQRequisitionId; 
            ViewData["requisitionNumber"] = Guid.Parse(TransactionNo);
            Guid requisitionNo = Guid.Parse(TransactionNo);
            var repositoryContext = _context.Requisition.ToList().Find(x => x.RequisitionNo == requisitionNo);
           // await SendRFQEmailAsync(Guid.Parse(TransactionNo), supplierDetails.SupplierId);
             SendRFQEmailAsync(Guid.Parse(TransactionNo) , supplierDetails.SupplierId);


            var notification = new Notification();
            notification.RequisitionId = repositoryContext.RequisitionId;
            //notification.To = supplierDetails.ContactPersonEmail;
            notification.To = "suppliersmail@yahoo.com"; 
            notification.Cc = repositoryContext.QueriesEmail;
            notification.From = User.Identity.Name;

            notification.Comment = "Approve";
            notification.Link = "N/A";
            //notification.Link = _configuration.GetValue<string>("ReqSubmissionSettings:ReqSubmissionLink").Replace("{RequisitionId}", $"{id}");
            //notification.Action = action;
            notification.Message = "Requisition approved by Line Manager:" + " " + notification.Link;
            notification.DateCreated = DateTime.Now;
            _context.Add(notification);
            await _context.SaveChangesAsync();

            return View("RFQSentConfirmation");
        }


        [HttpGet]
        [Route("ApplicationVerification")]
        public ActionResult CreateEditQuotations(Guid TransactionNo, int SupplierId)
        {
            //user is directed here via the email link, the create edit view is then displayed
            //https://localhost:44334/Quotations/CreateEditQuotation/?TransactionNo=
    
            return View (); 
        }
        //private async Task SendRFQEmailAsync(Guid TransactionNO , int SupplierId)
        private void SendRFQEmailAsync(Guid TransactionNO, int SupplierId)
        {

            var fromAddress = new MailAddress("qiscmapp@gmail.com", "From Name");

SupplyChainManagement/Views/Supplier/Details.cshtml
@model Entities.Models.Supplier

@{
    ViewData["Title"] = "Details";
    //Layout =   Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
    Layout = "~/Views/Shared/Uniform.cshtml";
}


<html>
<head>
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/assets/img/favicon.png">
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/assets/demo/demo.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/assets/demo/demo.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    @*<link href="~/assets/demo/demo.css" rel="stylesheet" />
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@



</head>
<body>
    <div class="content">

        <div class="container-fluid">
            <div style="font-family:'Times New Roman'">
                <h4>Supplier Details</h4>
                <hr />
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.SupplierName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.SupplierName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.LegalName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.LegalName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.RegistrationNo)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.RegistrationNo)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Vatregistered)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Vatregistered)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.VatregistrationNo)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.VatregistrationNo)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Bbbeeid)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Bbbeeid)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Currency)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Currency)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PaymentTermId)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PaymentTermId)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.StreetName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.StreetName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.BuildingName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.BuildingName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Surburb)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Surburb)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PostalCode)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PostalCode)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ContactPersonName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ContactPersonName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ContactPersonSurname)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ContactPersonSurname)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ContactPersonPosition)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ContactPersonPosition)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ContactPersonTelephone)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ContactPersonTelephone)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ContactPersonFax)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ContactPersonFax)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ContactPersonCell)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ContactPersonCell)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ContactPersonEmail)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ContactPersonEmail)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.QuotationContact)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.QuotationContact)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.City)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.City.CityName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Classification)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Classification.Description)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Country)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Country.CountryName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Municipality)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Municipality.MunicipalityAddress)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PaymentMethod)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PaymentMethod.Description)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Province)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Province.ProvinceName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Ward)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Ward.WardName)
                    </dd>
                </dl>
            </div>
            <div>
                <a asp-action="Index">Back to List</a>|
                <a asp-controller="Email" asp-action="SendEmail">Request for Quotation</a>

            </div>
        </div>
    </div>
</body>
</html>

SupplyChainManagement/Views/Supplier/Index.cshtml
@model IEnumerable<Entities.Models.Supplier>

@{
    ViewData["Title"] = "Index";
    //Layout =   Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
    //Layout = "~/Views/Shared/Uniform.cshtml";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/assets/img/favicon.png">
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/assets/demo/demo.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/assets/demo/demo.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    @*<link href="~/assets/demo/demo.css" rel="stylesheet" />
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@



</head>
<body>
   
    <div class="content">

        <div class="container-fluid">


            <div class="row">


                <div class="col-md-12">
                    <div class="card" style="font-family:'Times New Roman'">
                        <div class="card-header card-header-primary" style="background-color: #e0f0ff">
                            <h4 class="card-title">List Of Suppliers</h4>

                        </div>
                        <div class="card-body">
                            <form method="post" asp-controller="Supplier" asp-action="Search">
                                <div class="input-group">
                                    <input id="searchTerm" class="form-control" type="text" name="searchTerm">

                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="submit">
                                            Search
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.SupplierName)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.LegalName)
                                            </th>

                                            <th>
                                                @Html.DisplayNameFor(model => model.Country)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Province)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.City)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.SupplierName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.LegalName)
                                                </td>

                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Country.CountryName)
                                                </td>

                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Province.ProvinceName)
                                                </td>


                                                <td>
                                                    @Html.DisplayFor(modelItem => item.City.CityName)
                                                </td>
                                                <td>
                                                    <a asp-action="Details" asp-route-id="@item.SupplierId">Details</a>

                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</body>
</html>

SupplyChainManagement/Views/Supplier/RFQSentConfirmation.cshtml
@using Entities.Models
@model Entities.Models.Supplier;
@{
    ViewData["Title"] = "RFQ Confirmation";

    var Req = ViewData["requisitionNumber"].ToString();
    var ssd = (Supplier)ViewData["selectedSupplierDetails"];

    //Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<h1>RFQ Confirmation</h1>

<br />
<br />

<div class="container">
    <div class="master">
        <h3>Request For Confirmation Submission Successful!</h3>
        <br />
        <p>
            Thank you <b>@User.Identity.Name</b> You have successfully submitted your RFQ . The RFQ for Requisition Number <b>@Req </b>has been submitted to<b>@ssd.SupplierName </b> you will be provided with feedback shortly
            Following your application, one of our education consultants will be in contact with you to assist you with the registration process.
        </p>
        @*<p>
                Please be advised that your application for @Model.Qualification is currently in progress and being reviewed by the Regenesys Staff. Your reference number is: <strong>@Model.ApplicationReferenceNumber</strong><br /><br />
                For more details you can query by sending an email to: <strong>info@regenesys.co.za</strong> or call <strong>+27 0 11 669 5000.</strong><br /><br />

                Have a nice day.
            </p>*@

    </div>
</div>