SupplyChainManagement/Controllers/NotificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Entities;
using Entities.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Services;

namespace SupplyChainManagement.Controllers
{
    public class NotificationsController : Controller
    {
        private readonly RepositoryContext _context;
        private readonly IEmailSender _emailSender;
        private IConfiguration _configuration;

        private readonly UserManager<IdentityUser> _userManager;

        public static string Action;
        public static string From;
        public static string To;
        public static string Comment;
        public static DateTime DateCreated;
      
        // GET: NotificationsController

        public NotificationsController(RepositoryContext context, IEmailSender emailSender, IConfiguration iConfig, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _emailSender = emailSender;
            _configuration = iConfig;
            _userManager = userManager;
            //ViewData["MessageCount"] = 1;

        }
        public ActionResult Index()
        {
            return View();
        }

        // GET: NotificationsController/Details/5
        public ActionResult ReadNotifications(int? notificationId)
        {
            //place read noitfication value here
            // and return a list of where read = false
            
            var ViewNotification = _context.Notification.FirstOrDefault(x => x.NotificationId == notificationId);
            //Action = ViewNotification.;
            //From = ViewNotification.To;
            //Comment = ViewNotification.Comment;
            //DateCreated = ViewNotification.DateCreated; 
            //var check = ViewNotification.From;
            ViewData["notificationMessage"] = ViewNotification;
            return View(ViewNotification);
        }

        [HttpGet]
        public async Task<IActionResult> SubmitRequisition(int? id, string action, string comment)
        {

            if (id == null)
            {

                return NotFound();
            }

            var requisition = await _context.Requisition.FindAsync(id);
            if (requisition == null)
            {
                return NotFound();
            }

            return (await SubmitUserRequisition(id, action, comment));
        }

        [HttpPost]
        public async Task<IActionResult> SubmitUserRequisition(int? id, string action, string comment)
        {
            IdentityUser identityUser = await _userManager.GetUserAsync(User);

            string email = identityUser.Email;
            var requisition = _context.Requisition.Where(r => r.RequisitionId.Equals(id)).SingleOrDefault();
            if (ModelState.IsValid)
            {
                if (requisition.RequisitionId > 0)
                {
                    var notification = new Notification();
                    notification.RequisitionId = requisition.RequisitionId;
                    notification.DateCreated = DateTime.Now;
                    notification.From = email;
                    notification.To = "tinashe@qisolutions.co.za";
                    notification.Action = action;
                    notification.Comment = comment;
                    notification.Link = _configuration.GetValue<string>("RequisitionSettings:RedirectLink").Replace("{RequisitionId}", $"{id}");
                    notification.Message = "New requisition has been created:" + " " + notification.Link;
                    notification.IsRead.Equals(false);

                    _context.Add(notification);
                    await _context.SaveChangesAsync();
                    var rng = new Random();
                    SmtpClient client = new SmtpClient("smtp.office365.com")
                    {
                        //Port = 587, //outlook port 587
                        //Port = 587,
                        Port = 25,
                        EnableSsl = true,
                        //UseDefaultCredentials
                        UseDefaultCredentials = false,
                        TargetName = "STARTTLS/smtp.office365.com",
                        DeliveryMethod = SmtpDeliveryMethod.Network,
                        //Credentials = new NetworkCredential("tinashe@qisolutions.co.za","H#.VZlFCj$=c"),
                        Credentials = new NetworkCredential("thandeka@qisolutions.co.za", "MissT@2021!"),
                    };

                    MailMessage message = new MailMessage()
                    {
                        //From = new MailAddress(SubmissionNotfication.From), 
                        // From = new MailAddress("tinashe@qisolutions.co.za"),
                        From = new MailAddress("thandeka@qisolutions.co.za"),
                        //2.The authentication email address is the same as the emails "From" address.
                        Subject = "New Requisition",
                        Body = "New requisition has been created:" + " " + requisition.RequisitionNo,
                        IsBodyHtml = true,
                    };

                    message.To.Add("tinashe@qisolutions.co.za");
                    //message.CC.Add(SubmissionNotfication.Cc);
                    //var attachment = new System.Net.Mail.Attachment(filePath); //Attachment(string fileName, string mediaType) 
                    //message.Attachments.Add(attachment);
                    client.Send(message);
                }
                //var message = new Message(new string[] { notification.To }, "New Requisition", "New requisition has been created:" + " " + requisition.RequisitionNo, null);
                //    await _emailSender.SendEmailAsync(message);
               // }


            }
            return View();
        }

        // GET: NotificationsController/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var notification = await _context.Notification.FindAsync(id);
            if (notification == null)
            {
                return NotFound();
            }
            return (await Edit(id, notification));
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int? id, Notification notification)
        {
            if (id != notification.NotificationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {


                notification.IsRead = true;
                _context.Update(notification);
                await _context.SaveChangesAsync();

                //return RedirectToAction(nameof(Index));
            }
            return View(notification);
        }

        // GET: NotificationsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NotificationsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NotificationsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: NotificationsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NotificationsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: NotificationsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SupplyChainManagement/Views/Shared/AdminLTE/_Footer.cshtml
<footer class="main-footer">
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="https://supplychain">Suply  Chain</a>.</strong> All rights reserved.
</footer>

SupplyChainManagement/Views/Shared/AdminLTE/_Scripts.cshtml
<script src="~/plugins/jquery/jquery.min.js"></script>
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/js/adminlte.min.js"></script>

SupplyChainManagement/Views/Shared/AdminLTE/_Styles.cshtml
<link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
<link rel="stylesheet" href="~/css/adminlte.min.css">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

SupplyChainManagement/Views/Shared/AdminLTE/_TopNavigation.cshtml
@using Entities.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    //var requisitionDetails = ViewData["QualificationName"];
    //var MessageCount = ViewData["MessageCount"];
    var MessageCount = GlobalVariables.messageCount;
    //var MessageList = (List<Notification>)ViewData["MessageList"];
    var MessageList = GlobalVariables.messageList;
    //  (List<Notification>)ViewData["MessageList"];
    // GlobalVariables.messageList = (List(<MessageList>));


}

<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        @if (User.Identity.IsAuthenticated)
        {
<li class="nav-item d-none d-sm-inline-block">
    <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
        <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
    </form>
</li>
 }
else
{
<li class="nav-item d-none d-sm-inline-block">
    <a asp-area="Identity" asp-page="/Account/Login" class="nav-link">Login</a>
</li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a asp-area="Identity" asp-page="/Account/Register" class="nav-link">Register</a>
                </li>
}

    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">@MessageCount</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">(@MessageCount) Messages</span>
                <div class="dropdown-divider"></div>

                <a href="#" class="dropdown-item">
                    @if (ViewData["MessageList"] != null)
                    {
                        var viewDataProd = ViewData["MessageList"] as List<Notification>;
                        @for (var i = 0; i < viewDataProd.Count; i++)
                        {
                            <strong class="text-info">@viewDataProd[i].From</strong>
                            @if (User.IsInRole("CFO") || User.IsInRole("Manager") || User.IsInRole("CEO"))
                            {
                                if (viewDataProd[i].Message != null)
                                {
                <i class="fas fa-envelope mr-2">@Html.ActionLink(@viewDataProd[i].Action, "Details", "Requisition", routeValues: new { @viewDataProd[i].RequisitionId }, htmlAttributes: new { target = "_blank" })</i>
                                    <br /><small class="text-warning">27.11.2015, 15:00</small><br /><br />
                                }
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                if (viewDataProd[i].Message != null)
                                {
                                    <i class="fas fa-envelope mr-2">@Html.ActionLink(@viewDataProd[i].Action, "Edit", "Requisition", routeValues: new { @viewDataProd[i].RequisitionId }, htmlAttributes: new { target = "_blank" })</i>}
                                <br /><small class="text-warning">27.11.2015, 15:00</small><br /><br />
                            }

                        }

                        @if (GlobalVariables.messageList != null)


                            viewDataProd = GlobalVariables.messageList as List<Notification>;
                        @for (var i = 0; i < viewDataProd.Count; i++)
                        {
                            <i class="fas fa-envelope mr-2">
                                @Html.ActionLink(@viewDataProd[i].Action, "ReadNotifications", "Notifications", routeValues: new { @viewDataProd[i].NotificationId }, htmlAttributes: new { target = "_blank" })</i>
                            <br /><small class="text-warning">27.11.2015, 15:00</small><br /><br />
                        }
                    }
                    }


                    <strong class="text-info">David John</strong>
                    <div>
                        Lorem ipsum dolor sit amet, consectetur
                    </div>

                    <small class="text-warning">27.11.2015, 15:00</small>
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
</div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->